import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const helvetica = localFont({
  src: [
    {
      path: "../../public/fonts/helvetica/Helvetica.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/helvetica/Helvetica-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
  display: "swap",
  adjustFontFallback: "Times New Roman",
});

const akira = localFont({
  src: [
    {
      path: "../../public/fonts/Akira-Expanded.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-akira",
  display: "swap",
  adjustFontFallback: "Times New Roman",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${akira.variable} antialiased relative`}>
        {children}
      </body>
    </html>
  );
}
